pipeline {
    environment {
        IMAGE = "toleksa/${JOB_NAME}"
        CREDENTIALS = credentials('dockerhub')
        SUBDIR = "src/python-http"
    }
    agent{
        label ''
    }
    stages{
        stage('Build Docker Image') {
            stages{
                stage('Checkout'){
                    steps{
                        git url: 'https://github.com/toleksa/cicd.git', branch: 'main'
                        sh 'ls -la'
                        sh 'cat ${SUBDIR}/Dockerfile'
                    }
                }
                stage('Unit Test'){
                    steps{
                        sh 'echo "yeah, this test makes completely no sense :D"'
                        //sh 'cd ${SUBDIR} ; /usr/bin/python3 -m http.server 8888 &'
                        //sh 'python3 -m venv pytest'
                        //sh 'source pytest/bin/activate'
                        //sh 'pip install pytest-httpserver'
                        //sh 'python3 -m pytest ${SUBDIR}/www/test_mock.py"'
                        //sh 'python3 -m pytest ${SUBDIR}/www/test_web.py"'
                    }
                }
                stage('Build1'){
                    steps{
                        sh 'docker build -t ${IMAGE}:${BUILD_NUMBER} -f ${SUBDIR}/Dockerfile ${SUBDIR}/ '
                        sh 'docker tag ${IMAGE}:${BUILD_NUMBER} ${IMAGE}:latest '
                        sh 'docker images'
                    }
                }
                stage('Build2'){
                    steps{
                        script{
                            docker_image = docker.build("${IMAGE}:${BUILD_NUMBER}-2","${SUBDIR}")
                        }
                        sh 'docker images'
                    }
                }
            }
        }
        stage('Internal Test') { 
            agent {
                docker {
                    image "${IMAGE}:${BUILD_NUMBER}"
                    //args '--entrypoint='
                    //args '--entrypoint="/usr/bin/python3 -m http.server 80"'
                }
            }
            steps{
                sh 'cat /etc/os-release' 
                sh 'hostname'
                sh 'ls -la /www'
                sh 'nc -z localhost 80'
            }
        }
        stage('Curl Test') {
          steps {
            script {
              docker.image("${IMAGE}:${BUILD_NUMBER}").withRun('-p 8888:80') {
                sh 'curl localhost:8888'
                sh 'curl localhost:8888/logo.png -o /dev/null'
              }
            }
          }
        }   
        stage('External Test') {
          steps {
            script {
              network_name = "${BUILD_TAG}"
              sh "docker network create ${network_name}"
              docker.image("${IMAGE}:${BUILD_NUMBER}").withRun("-p 8888:80 --network ${network_name} --hostname webserver") {
                sh 'docker rmi pytest:latest'
                pytest_image = docker.build('pytest','src/pytest')
                pytest_image.inside("--network ${network_name}") {
                  sh 'pytest -o cache_dir=/tmp/.pytest_cache --junit-xml=test_web_result.xml /pytest/test_web.py'
                }
              }
              sh "docker network rm ${network_name}"
            }
          }
        }
        stage('Publish'){
            steps{
                script {
                    docker.withRegistry( '', 'dockerhub' ) {
                        docker_image.push()
                        docker_image.push('latest')
                    }
                }
            }
        }
        stage('Cleanup'){
            steps{
                sh 'hostname -f'
                sh '''#!/bin/bash
                      for IMG in $(docker images | grep 004_jenkinsfile | sort -r | tail -n +6 | gawk '{ print $1":"$2 }') ; do docker rmi $IMG ; done
                '''
                sh 'docker images'
            }
        }        
    }
}





